sudo: required
language: generic

services:
  - docker

env:
  - DIST=unstable
  - DIST=buster

script:
  - echo "Building docker image for distribution $DIST"
  - cd docker-debian-sbuild
  - sh ./build.sh $DIST

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push amubtdx/debian-sbuild-$DIST

