sudo: required
language: generic

env:
  - REPO=https://github.com/amurzeau/streamlink-debian VERSION=debian/0.8.1-4

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $USER
  - git clone --branch $VERSION "$REPO" checkout-dir && cd $_
  - export TARGET_DIST=$(dpkg-parsechangelog --show-field distribution)
  - export DIST=$(echo "$TARGET_DIST" | cut -d '-' -f 1)

script:
  - echo "Building for distribution $DIST ($TARGET_DIST)"
  - ../travis-build/build.sh $DIST $TARGET_DIST
  - export CHANGES_FILE=$(find . -type f -name '*.changes' -printf '%T@ %P\n' | sort -nr | awk '{print $2}' | head -1)
  - echo "$CHANGES_FILE" && cat "$CHANGES_FILE"

deploy:
  provider: script
  script: pwd && ls -l && echo ../travis-build/deploy.sh streamlink-debian "$TARGET_DIST" "$CHANGES_FILE"
  skip_cleanup: true
  on:
    tags: true
