sudo: required
language: generic

services:
  - docker

env:
  - DIST=unstable


script:
  - echo "Building docker image for distribution $DIST"
  - sh ../docker-sbuild-unstable/build.sh $DIST

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    #  - docker push amubtdx/debian-sbuild-$DIST

