# This is a basic workflow to help you get started with Actions

name: firefox-esr

# Controls when the workflow will run
# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - 'firefox-esr'
    tags:
      - 'firefox-esr/*'
  pull_request:
    branches:
      - 'firefox-esr'
    tags:
      - 'firefox-esr/*'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Linux build
  linux:
    uses: ./.github/workflows/debian-build.yml
    with:
      repo: https://github.com/amurzeau/firefox-debian
      version: 03da7e4afb7eb515838b30df0cfeaf26dd2c3620
      arch: i386
    secrets: inherit
