# This is a basic workflow to help you get started with Actions

name: streamlink

# Controls when the workflow will run
# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - 'streamlink'
    tags:
      - 'streamlink/*'
  pull_request:
    branches:
      - 'streamlink'
    tags:
      - 'streamlink/*'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Linux build
  linux:
    uses: ./.github/workflows/debian-build.yml
    with:
      repo: https://github.com/amurzeau/streamlink-debian
      version: refs/tags/debian/4.2.0-1
      arch: i386
    secrets: inherit
